// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: eightball/fortuneteller.proto

package types

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type Fortuneteller struct {
	Index   string `protobuf:"bytes,1,opt,name=index,proto3" json:"index,omitempty"`
	Owner   string `protobuf:"bytes,2,opt,name=owner,proto3" json:"owner,omitempty"`
	Fortune string `protobuf:"bytes,3,opt,name=fortune,proto3" json:"fortune,omitempty"`
	Expiry  string `protobuf:"bytes,4,opt,name=expiry,proto3" json:"expiry,omitempty"`
}

func (m *Fortuneteller) Reset()         { *m = Fortuneteller{} }
func (m *Fortuneteller) String() string { return proto.CompactTextString(m) }
func (*Fortuneteller) ProtoMessage()    {}
func (*Fortuneteller) Descriptor() ([]byte, []int) {
	return fileDescriptor_d7d32e2e8b7d6d46, []int{0}
}
func (m *Fortuneteller) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Fortuneteller) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Fortuneteller.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Fortuneteller) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Fortuneteller.Merge(m, src)
}
func (m *Fortuneteller) XXX_Size() int {
	return m.Size()
}
func (m *Fortuneteller) XXX_DiscardUnknown() {
	xxx_messageInfo_Fortuneteller.DiscardUnknown(m)
}

var xxx_messageInfo_Fortuneteller proto.InternalMessageInfo

func (m *Fortuneteller) GetIndex() string {
	if m != nil {
		return m.Index
	}
	return ""
}

func (m *Fortuneteller) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

func (m *Fortuneteller) GetFortune() string {
	if m != nil {
		return m.Fortune
	}
	return ""
}

func (m *Fortuneteller) GetExpiry() string {
	if m != nil {
		return m.Expiry
	}
	return ""
}

func init() {
	proto.RegisterType((*Fortuneteller)(nil), "charleenfei.icqics20cosmoverseworkshop.eightball.Fortuneteller")
}

func init() { proto.RegisterFile("eightball/fortuneteller.proto", fileDescriptor_d7d32e2e8b7d6d46) }

var fileDescriptor_d7d32e2e8b7d6d46 = []byte{
	// 235 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x90, 0x3d, 0x4e, 0xc3, 0x40,
	0x10, 0x85, 0xbd, 0xfc, 0x04, 0xb1, 0x12, 0x8d, 0x85, 0xd0, 0x36, 0xac, 0x10, 0x15, 0x8d, 0xbd,
	0x11, 0xdc, 0x80, 0x22, 0x07, 0xa0, 0xa4, 0x22, 0x5e, 0x26, 0xf1, 0x88, 0xb5, 0xc7, 0x99, 0xdd,
	0x10, 0xe7, 0x16, 0x1c, 0x8b, 0x32, 0x25, 0x25, 0xb2, 0x2f, 0x82, 0xd8, 0xfc, 0xb9, 0xfc, 0xde,
	0x48, 0x4f, 0xf3, 0x3d, 0x79, 0x0b, 0x38, 0x2f, 0x43, 0x31, 0x75, 0xce, 0xcc, 0x88, 0xc3, 0xb2,
	0x86, 0x00, 0xce, 0x01, 0xe7, 0x0d, 0x53, 0xa0, 0x74, 0x6c, 0xcb, 0x29, 0x3b, 0x80, 0x7a, 0x06,
	0x98, 0xa3, 0x5d, 0xa0, 0xf5, 0x8f, 0x63, 0x4b, 0xbe, 0xa2, 0x4f, 0x60, 0x0f, 0x2b, 0xe2, 0x0f,
	0x5f, 0x52, 0x93, 0x1f, 0x5a, 0xee, 0x2b, 0x79, 0x35, 0x19, 0x16, 0xa5, 0xd7, 0xf2, 0x1c, 0xeb,
	0x77, 0x68, 0x95, 0xb8, 0x13, 0x0f, 0x97, 0x2f, 0x5b, 0xf8, 0x4f, 0x69, 0x55, 0x03, 0xab, 0x93,
	0x6d, 0x1a, 0x21, 0x55, 0xf2, 0x62, 0xf7, 0x85, 0x3a, 0x8d, 0xf9, 0x1e, 0xd3, 0x1b, 0x39, 0x82,
	0xb6, 0x41, 0x5e, 0xab, 0xb3, 0x78, 0xd8, 0xd1, 0xf3, 0xdb, 0x77, 0xa7, 0xc5, 0xa6, 0xd3, 0xe2,
	0xb7, 0xd3, 0xe2, 0xab, 0xd7, 0xc9, 0xa6, 0xd7, 0xc9, 0x4f, 0xaf, 0x93, 0xd7, 0xc9, 0x1c, 0x43,
	0xb9, 0x2c, 0x72, 0x4b, 0x95, 0x19, 0x58, 0x18, 0xb4, 0x8b, 0x2c, 0x6a, 0x64, 0x47, 0x8f, 0x6c,
	0x2f, 0x62, 0x5a, 0x73, 0x1c, 0x24, 0xac, 0x1b, 0xf0, 0xc5, 0x28, 0x2e, 0xf1, 0xf4, 0x17, 0x00,
	0x00, 0xff, 0xff, 0xce, 0x65, 0x41, 0xca, 0x2a, 0x01, 0x00, 0x00,
}

func (m *Fortuneteller) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Fortuneteller) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Fortuneteller) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Expiry) > 0 {
		i -= len(m.Expiry)
		copy(dAtA[i:], m.Expiry)
		i = encodeVarintFortuneteller(dAtA, i, uint64(len(m.Expiry)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.Fortune) > 0 {
		i -= len(m.Fortune)
		copy(dAtA[i:], m.Fortune)
		i = encodeVarintFortuneteller(dAtA, i, uint64(len(m.Fortune)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Owner) > 0 {
		i -= len(m.Owner)
		copy(dAtA[i:], m.Owner)
		i = encodeVarintFortuneteller(dAtA, i, uint64(len(m.Owner)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Index) > 0 {
		i -= len(m.Index)
		copy(dAtA[i:], m.Index)
		i = encodeVarintFortuneteller(dAtA, i, uint64(len(m.Index)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintFortuneteller(dAtA []byte, offset int, v uint64) int {
	offset -= sovFortuneteller(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Fortuneteller) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Index)
	if l > 0 {
		n += 1 + l + sovFortuneteller(uint64(l))
	}
	l = len(m.Owner)
	if l > 0 {
		n += 1 + l + sovFortuneteller(uint64(l))
	}
	l = len(m.Fortune)
	if l > 0 {
		n += 1 + l + sovFortuneteller(uint64(l))
	}
	l = len(m.Expiry)
	if l > 0 {
		n += 1 + l + sovFortuneteller(uint64(l))
	}
	return n
}

func sovFortuneteller(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozFortuneteller(x uint64) (n int) {
	return sovFortuneteller(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Fortuneteller) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowFortuneteller
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Fortuneteller: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Fortuneteller: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Index", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFortuneteller
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthFortuneteller
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthFortuneteller
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Index = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Owner", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFortuneteller
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthFortuneteller
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthFortuneteller
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Owner = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Fortune", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFortuneteller
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthFortuneteller
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthFortuneteller
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Fortune = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Expiry", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFortuneteller
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthFortuneteller
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthFortuneteller
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Expiry = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipFortuneteller(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthFortuneteller
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipFortuneteller(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowFortuneteller
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowFortuneteller
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowFortuneteller
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthFortuneteller
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupFortuneteller
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthFortuneteller
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthFortuneteller        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowFortuneteller          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupFortuneteller = fmt.Errorf("proto: unexpected end of group")
)
