// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: eightball/v1/query.proto

package types

import (
	context "context"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-sdk/types/query"
	_ "github.com/gogo/protobuf/gogoproto"
	grpc1 "github.com/gogo/protobuf/grpc"
	proto "github.com/gogo/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// QueryParamsRequest is request type for the Query/Params RPC method.
type QueryParamsRequest struct {
}

func (m *QueryParamsRequest) Reset()         { *m = QueryParamsRequest{} }
func (m *QueryParamsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryParamsRequest) ProtoMessage()    {}
func (*QueryParamsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_81a760f2bfe25428, []int{0}
}
func (m *QueryParamsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsRequest.Merge(m, src)
}
func (m *QueryParamsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsRequest proto.InternalMessageInfo

// QueryParamsResponse is response type for the Query/Params RPC method.
type QueryParamsResponse struct {
	// params holds all the parameters of this module.
	Params Params `protobuf:"bytes,1,opt,name=params,proto3" json:"params"`
}

func (m *QueryParamsResponse) Reset()         { *m = QueryParamsResponse{} }
func (m *QueryParamsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryParamsResponse) ProtoMessage()    {}
func (*QueryParamsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_81a760f2bfe25428, []int{1}
}
func (m *QueryParamsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsResponse.Merge(m, src)
}
func (m *QueryParamsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsResponse proto.InternalMessageInfo

func (m *QueryParamsResponse) GetParams() Params {
	if m != nil {
		return m.Params
	}
	return Params{}
}

type QueryFortuneRequest struct {
	Owner string `protobuf:"bytes,1,opt,name=owner,proto3" json:"owner,omitempty"`
}

func (m *QueryFortuneRequest) Reset()         { *m = QueryFortuneRequest{} }
func (m *QueryFortuneRequest) String() string { return proto.CompactTextString(m) }
func (*QueryFortuneRequest) ProtoMessage()    {}
func (*QueryFortuneRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_81a760f2bfe25428, []int{2}
}
func (m *QueryFortuneRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryFortuneRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryFortuneRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryFortuneRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryFortuneRequest.Merge(m, src)
}
func (m *QueryFortuneRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryFortuneRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryFortuneRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryFortuneRequest proto.InternalMessageInfo

func (m *QueryFortuneRequest) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

type QueryFortuneResponse struct {
	Fortune Fortune `protobuf:"bytes,1,opt,name=fortune,proto3" json:"fortune"`
}

func (m *QueryFortuneResponse) Reset()         { *m = QueryFortuneResponse{} }
func (m *QueryFortuneResponse) String() string { return proto.CompactTextString(m) }
func (*QueryFortuneResponse) ProtoMessage()    {}
func (*QueryFortuneResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_81a760f2bfe25428, []int{3}
}
func (m *QueryFortuneResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryFortuneResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryFortuneResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryFortuneResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryFortuneResponse.Merge(m, src)
}
func (m *QueryFortuneResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryFortuneResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryFortuneResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryFortuneResponse proto.InternalMessageInfo

func (m *QueryFortuneResponse) GetFortune() Fortune {
	if m != nil {
		return m.Fortune
	}
	return Fortune{}
}

type QueryFortunesRequest struct {
}

func (m *QueryFortunesRequest) Reset()         { *m = QueryFortunesRequest{} }
func (m *QueryFortunesRequest) String() string { return proto.CompactTextString(m) }
func (*QueryFortunesRequest) ProtoMessage()    {}
func (*QueryFortunesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_81a760f2bfe25428, []int{4}
}
func (m *QueryFortunesRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryFortunesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryFortunesRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryFortunesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryFortunesRequest.Merge(m, src)
}
func (m *QueryFortunesRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryFortunesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryFortunesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryFortunesRequest proto.InternalMessageInfo

type QueryFortunesResponse struct {
	Fortunes []Fortune `protobuf:"bytes,1,rep,name=fortunes,proto3" json:"fortunes"`
}

func (m *QueryFortunesResponse) Reset()         { *m = QueryFortunesResponse{} }
func (m *QueryFortunesResponse) String() string { return proto.CompactTextString(m) }
func (*QueryFortunesResponse) ProtoMessage()    {}
func (*QueryFortunesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_81a760f2bfe25428, []int{5}
}
func (m *QueryFortunesResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryFortunesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryFortunesResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryFortunesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryFortunesResponse.Merge(m, src)
}
func (m *QueryFortunesResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryFortunesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryFortunesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryFortunesResponse proto.InternalMessageInfo

func (m *QueryFortunesResponse) GetFortunes() []Fortune {
	if m != nil {
		return m.Fortunes
	}
	return nil
}

func init() {
	proto.RegisterType((*QueryParamsRequest)(nil), "eightball.v1.QueryParamsRequest")
	proto.RegisterType((*QueryParamsResponse)(nil), "eightball.v1.QueryParamsResponse")
	proto.RegisterType((*QueryFortuneRequest)(nil), "eightball.v1.QueryFortuneRequest")
	proto.RegisterType((*QueryFortuneResponse)(nil), "eightball.v1.QueryFortuneResponse")
	proto.RegisterType((*QueryFortunesRequest)(nil), "eightball.v1.QueryFortunesRequest")
	proto.RegisterType((*QueryFortunesResponse)(nil), "eightball.v1.QueryFortunesResponse")
}

func init() { proto.RegisterFile("eightball/v1/query.proto", fileDescriptor_81a760f2bfe25428) }

var fileDescriptor_81a760f2bfe25428 = []byte{
	// 441 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x92, 0x4f, 0x6b, 0xd4, 0x40,
	0x18, 0xc6, 0x33, 0xd5, 0xfe, 0x71, 0xf4, 0x34, 0xa6, 0xb2, 0x46, 0x89, 0x35, 0x5e, 0x44, 0x31,
	0x43, 0x56, 0xfc, 0x73, 0xf0, 0x0f, 0x14, 0x14, 0x3c, 0x08, 0x75, 0x0f, 0x1e, 0xbc, 0x4d, 0x96,
	0xb7, 0x49, 0x30, 0x3b, 0x6f, 0x3a, 0x33, 0x49, 0x2d, 0xe2, 0xc5, 0x4f, 0x20, 0xf4, 0xe0, 0x47,
	0xf1, 0x2b, 0xf4, 0x58, 0xf0, 0xe2, 0x49, 0x64, 0xd7, 0x0f, 0x22, 0x9d, 0x4c, 0x96, 0x46, 0xca,
	0x2e, 0xf4, 0xb6, 0x3b, 0xcf, 0x6f, 0x9e, 0xe7, 0x79, 0xdf, 0x0c, 0x1d, 0x40, 0x91, 0xe5, 0x26,
	0x15, 0x65, 0xc9, 0x9b, 0x84, 0xef, 0xd5, 0xa0, 0x0e, 0xe2, 0x4a, 0xa1, 0x41, 0x76, 0x65, 0xae,
	0xc4, 0x4d, 0x12, 0xf8, 0x19, 0x66, 0x68, 0x05, 0x7e, 0xf2, 0xab, 0x65, 0x82, 0x9b, 0x19, 0x62,
	0x56, 0x02, 0x17, 0x55, 0xc1, 0x85, 0x94, 0x68, 0x84, 0x29, 0x50, 0x6a, 0xa7, 0xde, 0x1b, 0xa3,
	0x9e, 0xa0, 0xe6, 0xa9, 0xd0, 0xd0, 0x5a, 0xf3, 0x26, 0x49, 0xc1, 0x88, 0x84, 0x57, 0x22, 0x2b,
	0xa4, 0x85, 0x1d, 0x7b, 0xbd, 0xd7, 0xa3, 0x12, 0x4a, 0x4c, 0x3a, 0x9b, 0x1b, 0x3d, 0x69, 0x17,
	0x95, 0xa9, 0x25, 0x38, 0x31, 0xf2, 0x29, 0x7b, 0x77, 0xe2, 0xbc, 0x63, 0x6f, 0x8c, 0x60, 0xaf,
	0x06, 0x6d, 0xa2, 0x37, 0xf4, 0x6a, 0xef, 0x54, 0x57, 0x28, 0x35, 0xb0, 0x21, 0x5d, 0x6b, 0x9d,
	0x07, 0x64, 0x8b, 0xdc, 0xbd, 0x3c, 0xf4, 0xe3, 0xd3, 0x33, 0xc6, 0x2d, 0xbd, 0x7d, 0xf1, 0xe8,
	0xf7, 0x2d, 0x6f, 0xe4, 0xc8, 0xe8, 0xbe, 0xb3, 0x7a, 0xdd, 0xe6, 0xba, 0x04, 0xe6, 0xd3, 0x55,
	0xdc, 0x97, 0xa0, 0xac, 0xd3, 0xa5, 0x51, 0xfb, 0x27, 0x7a, 0x4b, 0xfd, 0x3e, 0xec, 0x82, 0x1f,
	0xd1, 0x75, 0xd7, 0xdb, 0x25, 0x6f, 0xf6, 0x93, 0x1d, 0xef, 0xa2, 0x3b, 0x36, 0xba, 0xd6, 0xb7,
	0x9b, 0x8f, 0xb7, 0x43, 0x37, 0xff, 0x3b, 0x77, 0x39, 0x4f, 0xe8, 0x46, 0xb7, 0x9f, 0x01, 0xd9,
	0xba, 0xb0, 0x2c, 0x68, 0x0e, 0x0f, 0x7f, 0xac, 0xd0, 0x55, 0x6b, 0xc9, 0xbe, 0x13, 0xba, 0xee,
	0x28, 0x76, 0xbb, 0x7f, 0xf9, 0x8c, 0x3d, 0x04, 0xd1, 0x22, 0xa4, 0x6d, 0x15, 0xbd, 0xfa, 0xfa,
	0xf3, 0xef, 0xe1, 0xca, 0x4b, 0xf6, 0x9c, 0x8f, 0x73, 0xa1, 0x4a, 0x00, 0xb9, 0x0b, 0x05, 0xb7,
	0x8f, 0xa3, 0x01, 0xa5, 0xe1, 0xc1, 0x3e, 0xaa, 0x8f, 0x3a, 0xc7, 0x8a, 0x9f, 0xf5, 0xa5, 0xf9,
	0x67, 0xbb, 0xdb, 0x2f, 0xec, 0x90, 0xd0, 0x8d, 0x6e, 0x62, 0xb6, 0x20, 0xb7, 0x5b, 0x53, 0x70,
	0x67, 0x21, 0xe3, 0xca, 0xbd, 0xb0, 0xe5, 0x9e, 0xb2, 0xc7, 0xe7, 0x2a, 0xa7, 0xb7, 0xdf, 0x1f,
	0x4d, 0x43, 0x72, 0x3c, 0x0d, 0xc9, 0x9f, 0x69, 0x48, 0xbe, 0xcd, 0x42, 0xef, 0x78, 0x16, 0x7a,
	0xbf, 0x66, 0xa1, 0xf7, 0xe1, 0x59, 0x56, 0x98, 0xbc, 0x4e, 0xe3, 0x31, 0x4e, 0x96, 0x7a, 0x7f,
	0x3a, 0xe5, 0x6e, 0x0e, 0x2a, 0xd0, 0xe9, 0x9a, 0x7d, 0xdf, 0x0f, 0xff, 0x05, 0x00, 0x00, 0xff,
	0xff, 0x4e, 0xba, 0xeb, 0xce, 0xa1, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	// Queries a Fortune by index.
	Fortune(ctx context.Context, in *QueryFortuneRequest, opts ...grpc.CallOption) (*QueryFortuneResponse, error)
	// Queries a list of Fortunes items.
	Fortunes(ctx context.Context, in *QueryFortunesRequest, opts ...grpc.CallOption) (*QueryFortunesResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) Fortune(ctx context.Context, in *QueryFortuneRequest, opts ...grpc.CallOption) (*QueryFortuneResponse, error) {
	out := new(QueryFortuneResponse)
	err := c.cc.Invoke(ctx, "/eightball.v1.Query/Fortune", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) Fortunes(ctx context.Context, in *QueryFortunesRequest, opts ...grpc.CallOption) (*QueryFortunesResponse, error) {
	out := new(QueryFortunesResponse)
	err := c.cc.Invoke(ctx, "/eightball.v1.Query/Fortunes", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	// Queries a Fortune by index.
	Fortune(context.Context, *QueryFortuneRequest) (*QueryFortuneResponse, error)
	// Queries a list of Fortunes items.
	Fortunes(context.Context, *QueryFortunesRequest) (*QueryFortunesResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) Fortune(ctx context.Context, req *QueryFortuneRequest) (*QueryFortuneResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Fortune not implemented")
}
func (*UnimplementedQueryServer) Fortunes(ctx context.Context, req *QueryFortunesRequest) (*QueryFortunesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Fortunes not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_Fortune_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryFortuneRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Fortune(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/eightball.v1.Query/Fortune",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Fortune(ctx, req.(*QueryFortuneRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_Fortunes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryFortunesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Fortunes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/eightball.v1.Query/Fortunes",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Fortunes(ctx, req.(*QueryFortunesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "eightball.v1.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Fortune",
			Handler:    _Query_Fortune_Handler,
		},
		{
			MethodName: "Fortunes",
			Handler:    _Query_Fortunes_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "eightball/v1/query.proto",
}

func (m *QueryParamsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryParamsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryFortuneRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryFortuneRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryFortuneRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Owner) > 0 {
		i -= len(m.Owner)
		copy(dAtA[i:], m.Owner)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Owner)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryFortuneResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryFortuneResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryFortuneResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Fortune.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryFortunesRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryFortunesRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryFortunesRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryFortunesResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryFortunesResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryFortunesResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Fortunes) > 0 {
		for iNdEx := len(m.Fortunes) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Fortunes[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func encodeVarintQuery(dAtA []byte, offset int, v uint64) int {
	offset -= sovQuery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *QueryParamsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryParamsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Params.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryFortuneRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Owner)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryFortuneResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Fortune.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryFortunesRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryFortunesResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Fortunes) > 0 {
		for _, e := range m.Fortunes {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	return n
}

func sovQuery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQuery(x uint64) (n int) {
	return sovQuery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *QueryParamsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryParamsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryFortuneRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryFortuneRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryFortuneRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Owner", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Owner = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryFortuneResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryFortuneResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryFortuneResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Fortune", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Fortune.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryFortunesRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryFortunesRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryFortunesRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryFortunesResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryFortunesResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryFortunesResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Fortunes", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Fortunes = append(m.Fortunes, Fortune{})
			if err := m.Fortunes[len(m.Fortunes)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQuery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQuery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQuery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQuery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQuery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQuery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQuery = fmt.Errorf("proto: unexpected end of group")
)
