// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: eightball/v1/tx.proto

package types

import (
	context "context"
	fmt "fmt"
	types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/gogo/protobuf/gogoproto"
	grpc1 "github.com/gogo/protobuf/grpc"
	proto "github.com/gogo/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type MsgFeelingLucky struct {
	Sender string `protobuf:"bytes,1,opt,name=sender,proto3" json:"sender,omitempty"`
	// TODO: non-nullable gogoproto
	Offering *types.Coin `protobuf:"bytes,2,opt,name=offering,proto3" json:"offering,omitempty"`
}

func (m *MsgFeelingLucky) Reset()         { *m = MsgFeelingLucky{} }
func (m *MsgFeelingLucky) String() string { return proto.CompactTextString(m) }
func (*MsgFeelingLucky) ProtoMessage()    {}
func (*MsgFeelingLucky) Descriptor() ([]byte, []int) {
	return fileDescriptor_0c6ea5d56f153e84, []int{0}
}
func (m *MsgFeelingLucky) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgFeelingLucky) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgFeelingLucky.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgFeelingLucky) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgFeelingLucky.Merge(m, src)
}
func (m *MsgFeelingLucky) XXX_Size() int {
	return m.Size()
}
func (m *MsgFeelingLucky) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgFeelingLucky.DiscardUnknown(m)
}

var xxx_messageInfo_MsgFeelingLucky proto.InternalMessageInfo

func (m *MsgFeelingLucky) GetSender() string {
	if m != nil {
		return m.Sender
	}
	return ""
}

func (m *MsgFeelingLucky) GetOffering() *types.Coin {
	if m != nil {
		return m.Offering
	}
	return nil
}

type MsgFeelingLuckyResponse struct {
}

func (m *MsgFeelingLuckyResponse) Reset()         { *m = MsgFeelingLuckyResponse{} }
func (m *MsgFeelingLuckyResponse) String() string { return proto.CompactTextString(m) }
func (*MsgFeelingLuckyResponse) ProtoMessage()    {}
func (*MsgFeelingLuckyResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0c6ea5d56f153e84, []int{1}
}
func (m *MsgFeelingLuckyResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgFeelingLuckyResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgFeelingLuckyResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgFeelingLuckyResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgFeelingLuckyResponse.Merge(m, src)
}
func (m *MsgFeelingLuckyResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgFeelingLuckyResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgFeelingLuckyResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgFeelingLuckyResponse proto.InternalMessageInfo

type MsgConnectToDex struct {
	Creator      string `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	ConnectionId string `protobuf:"bytes,2,opt,name=connection_id,json=connectionId,proto3" json:"connection_id,omitempty" yaml:"connection_id"`
}

func (m *MsgConnectToDex) Reset()         { *m = MsgConnectToDex{} }
func (m *MsgConnectToDex) String() string { return proto.CompactTextString(m) }
func (*MsgConnectToDex) ProtoMessage()    {}
func (*MsgConnectToDex) Descriptor() ([]byte, []int) {
	return fileDescriptor_0c6ea5d56f153e84, []int{2}
}
func (m *MsgConnectToDex) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgConnectToDex) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgConnectToDex.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgConnectToDex) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgConnectToDex.Merge(m, src)
}
func (m *MsgConnectToDex) XXX_Size() int {
	return m.Size()
}
func (m *MsgConnectToDex) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgConnectToDex.DiscardUnknown(m)
}

var xxx_messageInfo_MsgConnectToDex proto.InternalMessageInfo

func (m *MsgConnectToDex) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *MsgConnectToDex) GetConnectionId() string {
	if m != nil {
		return m.ConnectionId
	}
	return ""
}

type MsgConnectToDexResponse struct {
}

func (m *MsgConnectToDexResponse) Reset()         { *m = MsgConnectToDexResponse{} }
func (m *MsgConnectToDexResponse) String() string { return proto.CompactTextString(m) }
func (*MsgConnectToDexResponse) ProtoMessage()    {}
func (*MsgConnectToDexResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0c6ea5d56f153e84, []int{3}
}
func (m *MsgConnectToDexResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgConnectToDexResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgConnectToDexResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgConnectToDexResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgConnectToDexResponse.Merge(m, src)
}
func (m *MsgConnectToDexResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgConnectToDexResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgConnectToDexResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgConnectToDexResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*MsgFeelingLucky)(nil), "eightball.v1.MsgFeelingLucky")
	proto.RegisterType((*MsgFeelingLuckyResponse)(nil), "eightball.v1.MsgFeelingLuckyResponse")
	proto.RegisterType((*MsgConnectToDex)(nil), "eightball.v1.MsgConnectToDex")
	proto.RegisterType((*MsgConnectToDexResponse)(nil), "eightball.v1.MsgConnectToDexResponse")
}

func init() { proto.RegisterFile("eightball/v1/tx.proto", fileDescriptor_0c6ea5d56f153e84) }

var fileDescriptor_0c6ea5d56f153e84 = []byte{
	// 378 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x92, 0xcf, 0xea, 0xd3, 0x40,
	0x10, 0xc7, 0x1b, 0x85, 0x6a, 0xd7, 0x8a, 0x10, 0xaa, 0xa6, 0x05, 0x63, 0x09, 0x08, 0xbd, 0xb8,
	0x4b, 0x2a, 0x5e, 0x44, 0x2f, 0xad, 0x08, 0x82, 0xbd, 0x84, 0xe2, 0xc1, 0x8b, 0x26, 0xdb, 0xe9,
	0x66, 0x6d, 0xba, 0x13, 0xb2, 0xdb, 0xd8, 0xbe, 0x85, 0xaf, 0xe2, 0x5b, 0x78, 0xec, 0xd1, 0x93,
	0x48, 0xfb, 0x06, 0x3e, 0x81, 0x34, 0x69, 0xfa, 0xcf, 0xf2, 0xbb, 0xed, 0xfc, 0xe1, 0xfb, 0xf9,
	0xce, 0xec, 0x90, 0x87, 0x20, 0x45, 0x6c, 0xa2, 0x30, 0x49, 0x58, 0xee, 0x33, 0xb3, 0xa4, 0x69,
	0x86, 0x06, 0xed, 0xe6, 0x21, 0x4d, 0x73, 0xbf, 0xe3, 0x72, 0xd4, 0x73, 0xd4, 0x2c, 0x0a, 0x35,
	0xb0, 0xdc, 0x8f, 0xc0, 0x84, 0x3e, 0xe3, 0x28, 0x55, 0xd9, 0xdd, 0x69, 0x09, 0x14, 0x58, 0x3c,
	0xd9, 0xee, 0x55, 0x66, 0xbd, 0x2f, 0xe4, 0xc1, 0x48, 0x8b, 0x77, 0x00, 0x89, 0x54, 0xe2, 0xc3,
	0x82, 0xcf, 0x56, 0xf6, 0x23, 0x52, 0xd7, 0xa0, 0x26, 0x90, 0x39, 0x56, 0xd7, 0xea, 0x35, 0x82,
	0x7d, 0x64, 0xbf, 0x24, 0x77, 0x71, 0x3a, 0x85, 0x4c, 0x2a, 0xe1, 0xdc, 0xea, 0x5a, 0xbd, 0x7b,
	0xfd, 0x36, 0x2d, 0x99, 0x74, 0xc7, 0xa4, 0x7b, 0x26, 0x1d, 0xa2, 0x54, 0xc1, 0xa1, 0xd5, 0x6b,
	0x93, 0xc7, 0x17, 0x84, 0x00, 0x74, 0x8a, 0x4a, 0x83, 0xf7, 0xb5, 0x80, 0x0f, 0x51, 0x29, 0xe0,
	0x66, 0x8c, 0x6f, 0x61, 0x69, 0x3b, 0xe4, 0x0e, 0xcf, 0x20, 0x34, 0x58, 0xd1, 0xab, 0xd0, 0x7e,
	0x43, 0xee, 0xf3, 0xb2, 0x53, 0xa2, 0xfa, 0x2c, 0x27, 0x85, 0x87, 0xc6, 0xc0, 0xf9, 0xfb, 0xfb,
	0x69, 0x6b, 0x15, 0xce, 0x93, 0x57, 0xde, 0x59, 0xd9, 0x0b, 0x9a, 0xc7, 0xf8, 0xfd, 0x64, 0x6f,
	0xe3, 0x94, 0x55, 0xd9, 0xe8, 0xff, 0xb0, 0xc8, 0xed, 0x91, 0x16, 0xf6, 0x98, 0x34, 0xcf, 0x16,
	0xf1, 0x84, 0x9e, 0x2e, 0x98, 0x5e, 0x4c, 0xd1, 0x79, 0x76, 0x63, 0xb9, 0x52, 0xdf, 0xa9, 0x9e,
	0x4d, 0xf8, 0xbf, 0xea, 0x69, 0xf9, 0x8a, 0xea, 0x35, 0xcf, 0x83, 0x8f, 0x3f, 0x37, 0xae, 0xb5,
	0xde, 0xb8, 0xd6, 0x9f, 0x8d, 0x6b, 0x7d, 0xdf, 0xba, 0xb5, 0xf5, 0xd6, 0xad, 0xfd, 0xda, 0xba,
	0xb5, 0x4f, 0xaf, 0x85, 0x34, 0xf1, 0x22, 0xa2, 0x1c, 0xe7, 0x8c, 0xc7, 0x61, 0x96, 0x00, 0xa8,
	0x29, 0x48, 0x56, 0x7c, 0x55, 0x0e, 0x99, 0x86, 0xe7, 0xdf, 0x30, 0x9b, 0xe9, 0x18, 0x53, 0xb6,
	0x64, 0xc7, 0xcb, 0x32, 0xab, 0x14, 0x74, 0x54, 0x2f, 0xce, 0xe2, 0xc5, 0xbf, 0x00, 0x00, 0x00,
	0xff, 0xff, 0xdc, 0xbf, 0xe3, 0x93, 0x73, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MsgClient is the client API for Msg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MsgClient interface {
	FeelingLucky(ctx context.Context, in *MsgFeelingLucky, opts ...grpc.CallOption) (*MsgFeelingLuckyResponse, error)
	ConnectToDex(ctx context.Context, in *MsgConnectToDex, opts ...grpc.CallOption) (*MsgConnectToDexResponse, error)
}

type msgClient struct {
	cc grpc1.ClientConn
}

func NewMsgClient(cc grpc1.ClientConn) MsgClient {
	return &msgClient{cc}
}

func (c *msgClient) FeelingLucky(ctx context.Context, in *MsgFeelingLucky, opts ...grpc.CallOption) (*MsgFeelingLuckyResponse, error) {
	out := new(MsgFeelingLuckyResponse)
	err := c.cc.Invoke(ctx, "/eightball.v1.Msg/FeelingLucky", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) ConnectToDex(ctx context.Context, in *MsgConnectToDex, opts ...grpc.CallOption) (*MsgConnectToDexResponse, error) {
	out := new(MsgConnectToDexResponse)
	err := c.cc.Invoke(ctx, "/eightball.v1.Msg/ConnectToDex", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServer is the server API for Msg service.
type MsgServer interface {
	FeelingLucky(context.Context, *MsgFeelingLucky) (*MsgFeelingLuckyResponse, error)
	ConnectToDex(context.Context, *MsgConnectToDex) (*MsgConnectToDexResponse, error)
}

// UnimplementedMsgServer can be embedded to have forward compatible implementations.
type UnimplementedMsgServer struct {
}

func (*UnimplementedMsgServer) FeelingLucky(ctx context.Context, req *MsgFeelingLucky) (*MsgFeelingLuckyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FeelingLucky not implemented")
}
func (*UnimplementedMsgServer) ConnectToDex(ctx context.Context, req *MsgConnectToDex) (*MsgConnectToDexResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ConnectToDex not implemented")
}

func RegisterMsgServer(s grpc1.Server, srv MsgServer) {
	s.RegisterService(&_Msg_serviceDesc, srv)
}

func _Msg_FeelingLucky_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgFeelingLucky)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).FeelingLucky(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/eightball.v1.Msg/FeelingLucky",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).FeelingLucky(ctx, req.(*MsgFeelingLucky))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_ConnectToDex_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgConnectToDex)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).ConnectToDex(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/eightball.v1.Msg/ConnectToDex",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).ConnectToDex(ctx, req.(*MsgConnectToDex))
	}
	return interceptor(ctx, in, info, handler)
}

var _Msg_serviceDesc = grpc.ServiceDesc{
	ServiceName: "eightball.v1.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "FeelingLucky",
			Handler:    _Msg_FeelingLucky_Handler,
		},
		{
			MethodName: "ConnectToDex",
			Handler:    _Msg_ConnectToDex_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "eightball/v1/tx.proto",
}

func (m *MsgFeelingLucky) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgFeelingLucky) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgFeelingLucky) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Offering != nil {
		{
			size, err := m.Offering.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintTx(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.Sender) > 0 {
		i -= len(m.Sender)
		copy(dAtA[i:], m.Sender)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Sender)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgFeelingLuckyResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgFeelingLuckyResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgFeelingLuckyResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgConnectToDex) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgConnectToDex) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgConnectToDex) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.ConnectionId) > 0 {
		i -= len(m.ConnectionId)
		copy(dAtA[i:], m.ConnectionId)
		i = encodeVarintTx(dAtA, i, uint64(len(m.ConnectionId)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgConnectToDexResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgConnectToDexResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgConnectToDexResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func encodeVarintTx(dAtA []byte, offset int, v uint64) int {
	offset -= sovTx(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *MsgFeelingLucky) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Sender)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.Offering != nil {
		l = m.Offering.Size()
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgFeelingLuckyResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgConnectToDex) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.ConnectionId)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgConnectToDexResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func sovTx(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTx(x uint64) (n int) {
	return sovTx(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *MsgFeelingLucky) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgFeelingLucky: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgFeelingLucky: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Sender", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Sender = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Offering", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Offering == nil {
				m.Offering = &types.Coin{}
			}
			if err := m.Offering.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgFeelingLuckyResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgFeelingLuckyResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgFeelingLuckyResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgConnectToDex) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgConnectToDex: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgConnectToDex: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ConnectionId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ConnectionId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgConnectToDexResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgConnectToDexResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgConnectToDexResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTx(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTx
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTx
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTx
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTx
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTx        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTx          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTx = fmt.Errorf("proto: unexpected end of group")
)
