// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: eightball/v1/workflow.proto

package types

import (
	fmt "fmt"
	types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type Workflow struct {
	Offerer     string     `protobuf:"bytes,1,opt,name=offerer,proto3" json:"offerer,omitempty"`
	SwappedCoin types.Coin `protobuf:"bytes,2,opt,name=swapped_coin,json=swappedCoin,proto3" json:"swapped_coin"`
}

func (m *Workflow) Reset()         { *m = Workflow{} }
func (m *Workflow) String() string { return proto.CompactTextString(m) }
func (*Workflow) ProtoMessage()    {}
func (*Workflow) Descriptor() ([]byte, []int) {
	return fileDescriptor_8ae2990c229b64ff, []int{0}
}
func (m *Workflow) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Workflow) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Workflow.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Workflow) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Workflow.Merge(m, src)
}
func (m *Workflow) XXX_Size() int {
	return m.Size()
}
func (m *Workflow) XXX_DiscardUnknown() {
	xxx_messageInfo_Workflow.DiscardUnknown(m)
}

var xxx_messageInfo_Workflow proto.InternalMessageInfo

func (m *Workflow) GetOfferer() string {
	if m != nil {
		return m.Offerer
	}
	return ""
}

func (m *Workflow) GetSwappedCoin() types.Coin {
	if m != nil {
		return m.SwappedCoin
	}
	return types.Coin{}
}

func init() {
	proto.RegisterType((*Workflow)(nil), "eightball.v1.Workflow")
}

func init() { proto.RegisterFile("eightball/v1/workflow.proto", fileDescriptor_8ae2990c229b64ff) }

var fileDescriptor_8ae2990c229b64ff = []byte{
	// 256 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x44, 0x90, 0xbb, 0x4e, 0xf4, 0x30,
	0x10, 0x85, 0xe3, 0x5f, 0xbf, 0xb8, 0x64, 0xb7, 0x8a, 0x28, 0xc2, 0x22, 0x99, 0x15, 0xd5, 0x36,
	0x78, 0x14, 0x68, 0xa9, 0x96, 0x37, 0xd8, 0x02, 0x24, 0x1a, 0x14, 0x87, 0x49, 0x6c, 0x91, 0xcd,
	0x58, 0xb6, 0x49, 0xe0, 0x2d, 0x78, 0xac, 0x2d, 0xb7, 0xa4, 0x42, 0x28, 0x79, 0x11, 0x94, 0x0b,
	0xd0, 0x1d, 0x1f, 0xcf, 0x9c, 0x4f, 0x67, 0xc2, 0x33, 0xd4, 0x85, 0xf2, 0x32, 0x2d, 0x4b, 0xa8,
	0x13, 0x68, 0xc8, 0x3e, 0xe7, 0x25, 0x35, 0xc2, 0x58, 0xf2, 0x14, 0xcd, 0x7f, 0x3f, 0x45, 0x9d,
	0x2c, 0x78, 0x46, 0x6e, 0x4b, 0x0e, 0x64, 0xea, 0x10, 0xea, 0x44, 0xa2, 0x4f, 0x13, 0xc8, 0x48,
	0x57, 0xe3, 0xf4, 0xe2, 0xa4, 0xa0, 0x82, 0x06, 0x09, 0xbd, 0x1a, 0xdd, 0x0b, 0x15, 0x1e, 0xdd,
	0x4f, 0xa9, 0x51, 0x1c, 0x1e, 0x52, 0x9e, 0xa3, 0x45, 0x1b, 0xb3, 0x25, 0x5b, 0x1d, 0x6f, 0x7e,
	0x9e, 0xd1, 0x3a, 0x9c, 0xbb, 0x26, 0x35, 0x06, 0x9f, 0x1e, 0xfb, 0xc4, 0xf8, 0xdf, 0x92, 0xad,
	0x66, 0x57, 0xa7, 0x62, 0x44, 0x8a, 0x1e, 0x29, 0x26, 0xa4, 0xb8, 0x25, 0x5d, 0xad, 0xff, 0xef,
	0x3e, 0xcf, 0x83, 0xcd, 0x6c, 0x5a, 0x1a, 0xac, 0xbb, 0x5d, 0xcb, 0xd9, 0xbe, 0xe5, 0xec, 0xab,
	0xe5, 0xec, 0xbd, 0xe3, 0xc1, 0xbe, 0xe3, 0xc1, 0x47, 0xc7, 0x83, 0x87, 0x9b, 0x42, 0x7b, 0xf5,
	0x22, 0x45, 0x46, 0x5b, 0xc8, 0x54, 0x6a, 0x4b, 0xc4, 0x2a, 0x47, 0x0d, 0x43, 0x7a, 0x8d, 0xd6,
	0xe1, 0x65, 0xdf, 0xdc, 0x29, 0x32, 0xf0, 0x0a, 0x7f, 0x17, 0xf1, 0x6f, 0x06, 0x9d, 0x3c, 0x18,
	0x8a, 0x5c, 0x7f, 0x07, 0x00, 0x00, 0xff, 0xff, 0xc5, 0x1c, 0xf0, 0x7f, 0x2b, 0x01, 0x00, 0x00,
}

func (m *Workflow) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Workflow) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Workflow) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.SwappedCoin.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintWorkflow(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	if len(m.Offerer) > 0 {
		i -= len(m.Offerer)
		copy(dAtA[i:], m.Offerer)
		i = encodeVarintWorkflow(dAtA, i, uint64(len(m.Offerer)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintWorkflow(dAtA []byte, offset int, v uint64) int {
	offset -= sovWorkflow(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Workflow) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Offerer)
	if l > 0 {
		n += 1 + l + sovWorkflow(uint64(l))
	}
	l = m.SwappedCoin.Size()
	n += 1 + l + sovWorkflow(uint64(l))
	return n
}

func sovWorkflow(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozWorkflow(x uint64) (n int) {
	return sovWorkflow(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Workflow) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowWorkflow
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Workflow: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Workflow: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Offerer", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowWorkflow
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthWorkflow
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthWorkflow
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Offerer = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SwappedCoin", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowWorkflow
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthWorkflow
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthWorkflow
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.SwappedCoin.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipWorkflow(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthWorkflow
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipWorkflow(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowWorkflow
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowWorkflow
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowWorkflow
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthWorkflow
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupWorkflow
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthWorkflow
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthWorkflow        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowWorkflow          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupWorkflow = fmt.Errorf("proto: unexpected end of group")
)
